name: Release lightPDF

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.0.0
  workflow_dispatch: # Allows manual trigger from the GitHub UI

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Frontend Dependencies
        run: npm install

      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Download PDFium Engine
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" == "windows-latest" ]; then
            URL="https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-win-x64.tgz"
            LIB_FILE="pdfium.dll"
          elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
            URL="https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-mac-arm64.tgz"
            LIB_FILE="libpdfium.dylib"
          elif [ "${{ matrix.platform }}" == "ubuntu-22.04" ]; then
            URL="https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-linux-x64.tgz"
            LIB_FILE="libpdfium.so"
          fi
          curl -L -o pdfium.tgz $URL
          tar -xf pdfium.tgz
          mkdir -p src-tauri
          cp bin/$LIB_FILE src-tauri/

      - name: Build and Publish Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # The action automatically replaces \_\_VERSION\_\_ with the package.json version
          releaseName: 'lightPDF v__VERSION__'
          releaseBody: 'See the assets below to download and install this version.'
          releaseDraft: false
          prerelease: false