name: Release lightPDF

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.0.0
  workflow_dispatch: # Allows manual trigger from the GitHub UI

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build and Publish Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # The action automatically replaces \_\_VERSION\_\_ with the package.json version
          releaseName: 'lightPDF v__VERSION__'
          releaseBody: 'See the assets below to download and install this version.'
          releaseDraft: false
          prerelease: false